# Backtesting a Strategy

We are ready to backtest a simple trading strategy with **PyBroker**! Let's begin by importing the needed classes below:

In [1]:
import pybroker
from pybroker import Strategy, StrategyConfig, YFinance

pybroker.enable_data_source_cache('my_strategy')

[Yahoo Finance](https://finance.yahoo.com) will be used as the [DataSource](https://pybroker.com/en/latest/reference/pybroker.data.html#pybroker.data.DataSource) of our backtest. We also enable data source caching so that data is only downloaded one time when running backtests. 

The next step is to instantiate a new [Strategy](https://pybroker.com/en/latest/reference/pybroker.strategy.html#pybroker.strategy.Strategy) instance that will be used to backtest our trading strategy:

In [2]:
config = StrategyConfig(initial_cash=500_000)
strategy = Strategy(YFinance(), '3/1/2017', '3/1/2022', config)

The above creates a ```Strategy``` that will download data between ```3/1/2017``` and ```3/1/2022``` from Yahoo Finance before running a backtest. A [StrategyConfig](https://pybroker.com/en/latest/reference/pybroker.config.html#pybroker.config.StrategyConfig) is used to configure the ```Strategy```. By default, the [initial_cash](https://pybroker.com/en/latest/reference/pybroker.config.html#pybroker.config.StrategyConfig.initial_cash) to use for the backtest would be ```100_000```, but the config overrides the default with a value of ```500_000```.

## Defining Strategy Rules

Now, let's implement a basic trading strategy with the following rules:

- Buy shares in a stock if:

    - There is no open long position in that stock.
    
    - The last close price is less than the low of the previous bar.
    
- Set the limit price of the buy order to ```0.01``` less than the last close price.
- Hold the position for 3 days before liquidating it at the current market price.
- Trade the rules on ```AAPL``` and ```MSFT```, allocating up to 25% of the portfolio to each.

In [3]:
def buy_low(ctx):
    # If shares were already purchased and are currently being held, then return.
    if ctx.long_pos():
        return
    # If the latest close price is less than the previous day's low price,
    # then place a buy order.
    if len(ctx.low) >= 2 and ctx.close[-1] < ctx.low[-2]:
        # Buy a number of shares that is equal to 25% the portfolio.
        ctx.buy_shares = ctx.calc_target_shares(0.25)
        # Set the limit price of the order.
        ctx.buy_limit_price = ctx.close[-1] - 0.01
        # Hold the position for 3 bars before liquidating (in this case, 3 days).
        ctx.hold_bars = 3

The ```buy_low``` rules are then added to the ```Strategy``` for ```AAPL``` and ```MSFT``` using [add_execution](https://pybroker.com/en/latest/reference/pybroker.strategy.html#pybroker.strategy.Strategy.add_execution):

In [4]:
strategy.add_execution(buy_low, ['AAPL', 'MSFT'])

That is a lot to unpack! To fully understand how the above works, we need to step through **PyBroker's** execution model for running backtests.

When the backtest runs, the ```buy_low``` function will be called separately for ```AAPL``` and ```MSFT``` on every bar of data. Here, each bar corresponds to a single day of data for the ticker that was retrieved from Yahoo Finance.

An [ExecContext](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext) (```ctx```) will be passed to ```buy_low```. The ```ExecContext``` will contain data for the current ticker symbol being executed using the trading rules in ```buy_low```. For instance, [ctx.close](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.close) will contain all of the close prices up until the most recent bar of the current ticker symbol (```AAPL``` or ```MSFT```). The latest close price is retrieved with ```ctx.close[-1]```.

The ```ExecContext``` is also used to place a buy order. The number of shares to purchase is set in ```buy_low``` using [ctx.buy_shares](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.buy_shares), and the number of shares is calculated with [ctx.calc_target_shares](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.calc_target_shares). In this case, the number of shares to buy will be equal to 25% of the portfolio.

The limit price of the order is set by [buy_limit_price](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.buy_limit_price). If satisifed, the buy order will be filled on the next bar. The time when the order is filled can be configured with [StrategyConfig.buy_delay](https://pybroker.com/en/latest/reference/pybroker.config.html#pybroker.config.StrategyConfig.buy_delay), and its fill price can be set with [ExecContext.buy_fill_price](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.buy_fill_price). By default, buy orders are filled on the next bar (```buy_delay=1```) and at a [fill price equal to the midpoint between that bar's open and close price](https://pybroker.com/en/latest/reference/pybroker.common.html#pybroker.common.PriceType.MIDDLE).

Finally, [ctx.hold_bars](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.hold_bars) specifies how many bars to hold the position before liquidating it. When liquidating, the shares are sold at market price equal to [ExecContext.sell_fill_price](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext.sell_fill_price), which is configurable and also defaults to the midpoint between the bar's open and close price.

The ```ExecContext``` contains many other fields containing information about current positions, orders, OHLC prices and more. [You can read more on the reference documentation of ExecContext](https://pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext).

## Adding a Second Execution

We are not limited to only using one set of trading rules for one group of tickers. Another execution that implements different trading rules for different tickers can be added to the ```Strategy```.

Let's implement another set of trading rules that are similar as before, but are for a short strategy:

In [5]:
def short_high(ctx):
    # If shares were already shorted and that position is currently being held, then return.
    if ctx.short_pos():
        return
    # If the latest close price is more than the previous day's high price,
    # then place a sell order.
    if len(ctx.high) >= 2 and ctx.close[-1] > ctx.high[-2]:
        # Short 100 shares.
        ctx.sell_shares = 100
        # Cover the shares after 2 bars (in this case, 2 days).
        ctx.hold_bars = 2

And let's trade these rules on ```TSLA```:

In [6]:
strategy.add_execution(short_high, ['TSLA'])

## Running a Backtest

Running a backtest can be done by calling the [backtest](https://pybroker.com/en/latest/reference/pybroker.strategy.html#pybroker.strategy.Strategy.backtest) method on the ```Strategy```:

In [7]:
result = strategy.backtest(calc_bootstrap=False)

Backtesting: 2017-03-01 00:00:00 to 2022-03-01 00:00:00

Downloading bar data...
[*********************100%***********************]  3 of 3 completed
Finished download: 0:00:02

Test split: 2017-03-01 05:00:00 to 2022-02-28 05:00:00

100% (1259 of 1259) |####################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:05

That was fast! Notice that an argument ```calc_bootstrap=False``` was passed in to disable calculating bootstrap metrics. We can ignore that for now until the next notebook about bootstrap metrics.

The ```result``` returned is an instance of [TestResult](https://pybroker.com/en/latest/reference/pybroker.strategy.html#pybroker.strategy.TestResult). Let's take a look at the results, starting with the daily balances of our portfolio:

In [8]:
result.portfolio

,cash,equity,margin,market_value,pnl,unrealized_pnl
date,,,,,,
2017-03-01 05:00:00,500000.00,500000.00,0.00,500000.00,0.00,0.00
2017-03-02 05:00:00,500000.00,500000.00,0.00,500000.00,0.00,0.00
2017-03-03 05:00:00,375169.60,500585.60,0.00,500585.60,0.00,585.60
2017-03-06 05:00:00,375169.60,500624.63,0.00,500624.63,0.00,624.63
2017-03-07 05:00:00,375169.60,500878.40,0.00,500878.40,0.00,878.40
...,...,...,...,...,...,...
2022-02-22 05:00:00,327443.87,675653.40,0.00,675653.40,181339.03,-5685.63
2022-02-23 05:00:00,327443.87,666642.14,0.00,666642.14,181339.03,-14696.89
2022-02-24 05:00:00,665740.20,665740.20,0.00,665740.20,165740.20,0.00
2022-02-25 05:00:00,665740.20,665740.20,0.00,665740.20,165740.20,0.00
2022-02-28 05:00:00,693933.20,693933.20,29014.33,693111.87,165740.20,-821.33

Likewise, the result contains the daily balance of each position that was held:

In [9]:
result.positions

                            long_shares  short_shares   close     equity  \
symbol date
MSFT   2017-03-03 05:00:00         1952             0   64.25  125416.00
       2017-03-06 05:00:00         1952             0   64.27  125455.03
       2017-03-07 05:00:00         1952             0   64.40  125708.80
       2017-03-14 04:00:00         1937             0   64.41  124762.18
       2017-03-15 04:00:00         1937             0   64.75  125420.75
...                                 ...           ...     ...        ...
       2022-02-22 05:00:00          610             0  287.72  175509.20
AAPL   2022-02-22 05:00:00         1051             0  164.32  172700.33
MSFT   2022-02-23 05:00:00          610             0  280.27  170964.69
AAPL   2022-02-23 05:00:00         1051             0  160.07  168233.58
TSLA   2022-02-28 05:00:00            0           100  290.14       0.00

                            market_value    margin  unrealized_pnl
symbol date
MSFT   2017-03-03 05:00:00     125416.00      0.00          585.60
       2017-03-06 05:00:00     125455.03      0.00          624.63
       2017-03-07 05:00:00     125708.80      0.00          878.40
       2017-03-14 04:00:00     124762.18      0.00          116.23
       2017-03-15 04:00:00     125420.75      0.00          774.80
...                                  ...       ...             ...
       2022-02-22 05:00:00     175509.20      0.00        -1439.60
AAPL   2022-02-22 05:00:00     172700.33      0.00        -4246.03
MSFT   2022-02-23 05:00:00     170964.69      0.00        -5984.11
AAPL   2022-02-23 05:00:00     168233.58      0.00        -8712.78
TSLA   2022-02-28 05:00:00       -821.33  29014.33         -821.33

[938 rows x 7 columns]

And all of the orders that were placed, too:

In [10]:
result.orders

,date,symbol,order_type,limit_price,fill_price,shares,pnl,pnl %
id,,,,,,,,
1,2017-03-03 05:00:00,MSFT,buy,64.00,63.95,1952,0.00,0.000000
2,2017-03-08 05:00:00,MSFT,sell,NaN,64.67,1952,1405.44,95.601009
3,2017-03-14 04:00:00,MSFT,buy,64.70,64.35,1937,0.00,0.000000
4,2017-03-15 04:00:00,TSLA,sell,NaN,17.18,100,0.00,0.000000
5,2017-03-17 04:00:00,MSFT,sell,NaN,64.96,1937,1181.57,94.788734
...,...,...,...,...,...,...,...,...
773,2022-02-18 05:00:00,AAPL,buy,168.87,168.36,1051,0.00,0.000000
774,2022-02-18 05:00:00,MSFT,buy,290.72,290.08,610,0.00,0.000000
775,2022-02-24 05:00:00,AAPL,sell,NaN,157.43,1051,-11487.43,-98.648073
776,2022-02-24 05:00:00,MSFT,sell,NaN,283.34,610,-4111.40,-93.552747
777,2022-02-28 05:00:00,TSLA,sell,NaN,281.93,100,0.00,0.000000

The result also contains a DataFrame of metrics calculated on the out-of-sample results of the backtest:

In [11]:
result.metrics_df

                name          value
0        trade_count     777.000000
1      initial_value  500000.000000
2          end_value  693111.870000
3       total_profit  403511.080000
4         total_loss -237770.880000
5       max_drawdown  -56721.600000
6   max_drawdown_pct      -7.908429
7           win_rate       0.525773
8          loss_rate       0.474227
9         avg_profit    1977.995490
10    avg_profit_pct      78.814508
11          avg_loss   -1292.233043
12      avg_loss_pct     -74.109574
13       largest_win   21069.630000
14      largest_loss  -11487.430000
15          max_wins       3.000000
16        max_losses       3.000000
17            sharpe       0.017108
18     profit_factor       0.073193
19       ulcer_index       1.898348
20               upi       0.018445
21                r2       0.897905
22         std_error   69646.361297

[You can read about what these metrics mean here](https://pybroker.com/en/latest/reference/pybroker.eval.html#pybroker.eval.EvalMetrics).

## Filtering Backtest Data

Lastly, it is possible to filter the data used for the backtest. For example, the data can be filtered to only contain bars for Mondays. This, in effect, limits the strategy to only trade on Mondays:

In [12]:
result = strategy.backtest(days='mon', train_size=0.5, calc_bootstrap=False)
result.metrics_df

Backtesting: 2017-03-01 00:00:00 to 2022-03-01 00:00:00

Loaded cached bar data.

Test split: 2019-09-09 04:00:00 to 2022-02-28 05:00:00

100% (119 of 119) |######################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

                name          value
0        trade_count      96.000000
1      initial_value  500000.000000
2          end_value  524766.210000
3       total_profit   92139.090000
4         total_loss  -70520.750000
5       max_drawdown  -51841.520000
6   max_drawdown_pct     -10.186922
7           win_rate       0.510638
8          loss_rate       0.489362
9         avg_profit    3839.128750
10    avg_profit_pct      86.513448
11          avg_loss   -3066.119565
12      avg_loss_pct     -89.477227
13       largest_win   15766.960000
14      largest_loss  -22673.800000
15          max_wins       3.000000
16        max_losses       1.000000
17            sharpe       0.013561
18     profit_factor       0.039596
19       ulcer_index       3.947869
20               upi       0.021971
21                r2       0.317799
22         std_error   21225.992733

Note that the data did not need to be downloaded again from Yahoo Finance, since ```DataSource``` caching was enabled and because the cached data only needed to be filtered.

From the above, it seems like we already have a profitable strategy. But not so fast! We may be getting fooled by randomness. [Next, we will learn about using bootstrapping to further evaluate our trading strategies](https://pybroker.com/en/latest/notebooks/3.%20Evaluating%20a%20Strategy%20using%20Bootstrap%20Metrics.html).