# Applying Stops

Stops are used to automatically buy or sell a security once it reaches a specified price level. They can be useful for limiting potential losses by allowing traders to exit bad trades automatically, as well as for taking profits by selling a security automatically when it reaches a certain price level.

**PyBroker** supports the simulation of stops, which is explained in detail in this notebook:

In [1]:
import pybroker
from pybroker import Strategy, YFinance

pybroker.enable_data_source_cache('stops')

strategy = Strategy(YFinance(), '1/1/2018', '1/1/2023')

## Stop Loss

A stop loss order is used to automatically exit a trade once the security's price reaches or falls below a specified level. For example, the following code shows an example of a stop loss order set at ``20%`` below the entry price:

In [2]:
def buy_with_stop_loss(ctx):
    if not ctx.long_pos():
        ctx.buy_shares = ctx.calc_target_shares(1)
        ctx.stop_loss_pct = 20
        
strategy.add_execution(buy_with_stop_loss, ['TSLA'])
result = strategy.backtest()
result.trades

Backtesting: 2018-01-01 00:00:00 to 2023-01-01 00:00:00

Loading bar data...
[*********************100%***********************]  1 of 1 completed
Loaded bar data: 0:00:00

Test split: 2018-01-02 00:00:00 to 2022-12-30 00:00:00

100% (1259 of 1259) |####################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:02

,type,symbol,entry_date,exit_date,entry,exit,shares,pnl,return_pct,agg_pnl,bars,pnl_per_bar,stop
id,,,,,,,,,,,,,
1,long,TSLA,2018-01-03,2018-03-28,21.36,17.09,4679,-19988.69,-20.0,-19988.69,58,-344.63,loss
2,long,TSLA,2018-03-29,2019-05-20,17.31,13.85,4622,-16001.36,-20.0,-35990.05,286,-55.95,loss

## Take Profit

Similarly, a take profit order can be used to lock in profits on a trade. The following code adds a take profit order at ``10%`` above the entry price:

In [3]:
def buy_with_stop_loss_and_profit(ctx):
    if not ctx.long_pos():
        ctx.buy_shares = ctx.calc_target_shares(1)
        ctx.stop_loss_pct = 20
        ctx.stop_profit_pct = 10
        
strategy.clear_executions()
strategy.add_execution(buy_with_stop_loss_and_profit, ['TSLA'])
result = strategy.backtest()
result.trades

Backtesting: 2018-01-01 00:00:00 to 2023-01-01 00:00:00

Loaded cached bar data.

Test split: 2018-01-02 00:00:00 to 2022-12-30 00:00:00

100% (1259 of 1259) |####################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

,type,symbol,entry_date,exit_date,entry,exit,shares,pnl,return_pct,agg_pnl,bars,pnl_per_bar,stop
id,,,,,,,,,,,,,
1,long,TSLA,2018-01-03,2018-01-22,21.36,23.50,4679,9994.34,10.0,9994.34,12,832.86,profit
2,long,TSLA,2018-01-23,2018-03-27,23.72,18.98,4637,-21997.93,-20.0,-12003.58,44,-499.95,loss
3,long,TSLA,2018-03-28,2018-04-04,17.36,19.10,4727,8206.07,10.0,-3797.51,4,2051.52,profit
4,long,TSLA,2018-04-05,2018-06-07,19.82,21.80,4853,9618.65,10.0,5821.13,44,218.61,profit
5,long,TSLA,2018-06-08,2018-06-12,21.39,23.53,4947,10581.63,10.0,16402.77,2,5290.82,profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,long,TSLA,2022-07-29,2022-10-07,288.71,230.97,957,-55259.09,-20.0,121046.74,49,-1127.74,loss
86,long,TSLA,2022-10-10,2022-11-09,222.68,178.14,990,-44090.64,-20.0,76956.10,22,-2004.12,loss
87,long,TSLA,2022-11-10,2022-12-19,185.51,148.41,953,-35358.21,-20.0,41597.90,26,-1359.93,loss
88,long,TSLA,2022-12-20,2022-12-27,143.07,114.46,944,-27011.62,-20.0,14586.28,4,-6752.90,loss
89,long,TSLA,2022-12-28,2022-12-29,112.25,123.48,1020,11449.50,10.0,26035.78,1,11449.50,profit

## Trailing Stop

A trailing stop is an order that is used to exit a trade once the instrument's price falls a certain percentage or cash amount below its highest market price. Here is an example of setting a trailing stop at ``20%`` below the highest market price:

In [4]:
def buy_with_trailing_stop_loss_and_profit(ctx):
    if not ctx.long_pos():
        ctx.buy_shares = ctx.calc_target_shares(1)
        ctx.stop_trailing_pct = 20
        ctx.stop_profit_pct = 10
        
strategy.clear_executions()
strategy.add_execution(buy_with_trailing_stop_loss_and_profit, ['TSLA'])
result = strategy.backtest()
result.trades

Backtesting: 2018-01-01 00:00:00 to 2023-01-01 00:00:00

Loaded cached bar data.

Test split: 2018-01-02 00:00:00 to 2022-12-30 00:00:00

100% (1259 of 1259) |####################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

,type,symbol,entry_date,exit_date,entry,exit,shares,pnl,return_pct,agg_pnl,bars,pnl_per_bar,stop
id,,,,,,,,,,,,,
1,long,TSLA,2018-01-03,2018-01-22,21.36,23.50,4679,9994.34,10.00,9994.34,12,832.86,profit
2,long,TSLA,2018-01-23,2018-03-27,23.72,19.20,4637,-20961.72,-19.06,-10967.37,44,-476.40,trailing
3,long,TSLA,2018-03-28,2018-04-04,17.36,19.10,4783,8303.29,10.00,-2664.08,4,2075.82,profit
4,long,TSLA,2018-04-05,2018-06-07,19.82,21.80,4910,9731.62,10.00,7067.54,44,221.17,profit
5,long,TSLA,2018-06-08,2018-06-12,21.39,23.53,5005,10705.70,10.00,17773.23,2,5352.85,profit
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,long,TSLA,2022-08-02,2022-10-03,300.25,251.73,1016,-49292.94,-16.16,155981.76,43,-1146.35,trailing
103,long,TSLA,2022-10-04,2022-10-24,249.75,199.80,1024,-51148.80,-20.00,104832.96,14,-3653.49,trailing
104,long,TSLA,2022-10-25,2022-11-08,217.18,189.92,943,-25706.18,-12.55,79126.77,10,-2570.62,trailing
105,long,TSLA,2022-11-09,2022-12-13,186.50,160.66,936,-24189.98,-13.86,54936.79,23,-1051.74,trailing
106,long,TSLA,2022-12-14,2022-12-22,158.46,128.79,962,-28540.61,-18.72,26396.18,6,-4756.77,trailing

## Setting a Limit Price

A stop order can be combined with a limit price to ensure that the order is executed only at a specific price level. Below shows an example of placing a limit price on a stop order:

In [5]:
def buy_with_trailing_stop_loss_and_profit(ctx):
    if not ctx.long_pos():
        ctx.buy_shares = ctx.calc_target_shares(1)
        ctx.stop_trailing_pct = 20
        ctx.stop_trailing_limit = ctx.close[-1] + 1
        ctx.stop_profit_pct = 10
        ctx.stop_profit_limit = ctx.close[-1] - 1
        
strategy.clear_executions()
strategy.add_execution(buy_with_trailing_stop_loss_and_profit, ['TSLA'])
result = strategy.backtest()
result.trades

Backtesting: 2018-01-01 00:00:00 to 2023-01-01 00:00:00

Loaded cached bar data.

Test split: 2018-01-02 00:00:00 to 2022-12-30 00:00:00

100% (1259 of 1259) |####################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

,type,symbol,entry_date,exit_date,entry,exit,shares,pnl,return_pct,agg_pnl,bars,pnl_per_bar,stop
id,,,,,,,,,,,,,
1,long,TSLA,2018-01-03,2018-01-22,21.36,23.50,4679,9994.34,10.0,9994.34,12,832.86,profit
2,long,TSLA,2018-01-23,2019-12-18,23.72,26.09,4637,10998.96,10.0,20993.31,480,22.91,profit
3,long,TSLA,2019-12-19,2020-01-03,26.78,29.46,4518,12099.20,10.0,33092.51,9,1344.36,profit
4,long,TSLA,2020-01-06,2020-01-08,29.72,32.69,4478,13308.62,10.0,46401.13,2,6654.31,profit
5,long,TSLA,2020-01-09,2020-01-14,32.39,35.63,4462,14452.42,10.0,60853.55,3,4817.47,profit
6,long,TSLA,2020-01-15,2020-01-22,35.15,38.67,4485,15764.78,10.0,76618.32,4,3941.19,profit
7,long,TSLA,2020-01-23,2020-01-30,37.92,41.71,4651,17636.59,10.0,94254.91,5,3527.32,profit
8,long,TSLA,2020-01-31,2020-02-03,42.85,47.14,4533,19423.91,10.0,113678.82,1,19423.91,profit
9,long,TSLA,2020-02-04,2020-06-10,60.10,66.11,3555,21365.55,10.0,135044.37,88,242.79,profit
10,long,TSLA,2020-06-11,2020-07-01,66.37,73.01,3439,22824.64,10.0,157869.01,14,1630.33,profit
11,long,TSLA,2020-07-02,2020-07-06,80.45,88.50,3205,25784.23,10.0,183653.24,1,25784.23,profit
12,long,TSLA,2020-07-07,2020-07-10,92.21,101.43,3076,28363.80,10.0,212017.03,3,9454.60,profit
13,long,TSLA,2020-07-13,2020-08-17,108.87,119.76,2865,31191.26,10.0,243208.29,25,1247.65,profit
14,long,TSLA,2020-08-18,2020-08-21,125.63,138.19,2731,34309.55,10.0,277517.84,3,11436.52,profit
15,long,TSLA,2020-08-24,2020-08-27,135.22,148.74,2762,37347.76,10.0,314865.60,3,12449.25,profit
16,long,TSLA,2020-08-28,2020-08-31,150.17,165.19,2762,41476.95,10.0,356342.56,1,41476.95,profit
17,long,TSLA,2020-09-01,2020-11-24,162.17,178.39,2747,44548.10,10.0,400890.66,59,755.05,profit
18,long,TSLA,2020-11-25,2020-12-07,186.56,205.22,2684,50072.70,10.0,450963.36,7,7153.24,profit
19,long,TSLA,2020-12-08,2020-12-31,211.63,232.79,2575,54494.73,10.0,505458.09,16,3405.92,profit
20,long,TSLA,2021-01-04,2021-01-07,243.61,267.97,2485,60537.09,10.0,565995.17,3,20179.03,profit
21,long,TSLA,2021-01-08,2021-10-25,287.15,315.87,2319,66590.09,10.0,632585.26,200,332.95,profit
22,long,TSLA,2021-10-26,2021-11-01,349.40,384.34,2096,73234.24,10.0,705819.50,4,18308.56,profit

## Canceling a Stop

The following code shows an example of canceling a stop order:

In [6]:
def buy_with_stop_trailing_and_cancel(ctx):
    pos = ctx.long_pos()
    if not pos:
        ctx.buy_shares = ctx.calc_target_shares(1)
        ctx.stop_trailing_pct = 20
    elif pos.bars > 60:
        ctx.cancel_stops(ctx.symbol)
        
strategy.clear_executions()
strategy.add_execution(buy_with_stop_trailing_and_cancel, ['TSLA'])
result = strategy.backtest()
result.trades

Backtesting: 2018-01-01 00:00:00 to 2023-01-01 00:00:00

Loaded cached bar data.

Test split: 2018-01-02 00:00:00 to 2022-12-30 00:00:00

100% (1259 of 1259) |####################| Elapsed Time: 0:00:00 Time:  0:00:00

Finished backtest: 0:00:00

,type,symbol,entry_date,exit_date,entry,exit,shares,pnl,return_pct,agg_pnl,bars,pnl_per_bar,stop
id,,,,,,,,,,,,,
1,long,TSLA,2018-01-03,2018-03-27,21.36,19.23,4679,-9981.87,-9.99,-9981.87,57,-175.12,trailing

[For more information on the various attributes that can be used to set stops in PyBroker, you can refer to the ExecContext reference documentation.](https://www.pybroker.com/en/latest/reference/pybroker.context.html#pybroker.context.ExecContext)